//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matieres
    {
        public int numMatiere { get; set; }
        public string nomMatiere { get; set; }
        public Nullable<int> nbNote { get; set; }
        public Nullable<int> poidsMatiere { get; set; }
    }
}
