//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nsLibraryDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modules
    {
        public Modules()
        {
            this.Eleves = new HashSet<Eleves>();
        }
    
        public int numModule { get; set; }
        public string nomModule { get; set; }
        public Nullable<int> nbMatiere { get; set; }
        public Nullable<int> fknumMatiere { get; set; }
    
        public virtual ICollection<Eleves> Eleves { get; set; }
        public virtual Matieres Matieres { get; set; }
    }
}
