//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entityBDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matieres
    {
        public Matieres()
        {
            this.Notes = new HashSet<Notes>();
        }
    
        public int numMatiere { get; set; }
        public Nullable<int> fknumModule { get; set; }
        public string nomMatiere { get; set; }
        public Nullable<int> nbNote { get; set; }
        public int poidsMatiere { get; set; }
    
        public virtual Modules Modules { get; set; }
        public virtual ICollection<Notes> Notes { get; set; }
    }
}
