//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entityBDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        public Module()
        {
            this.Matiere = new HashSet<Matiere>();
            this.Eleve = new HashSet<Eleve>();
        }
    
        public int numModule { get; set; }
        public string nomModule { get; set; }
        public Nullable<int> nbMatiere { get; set; }
    
        public virtual ICollection<Matiere> Matiere { get; set; }
        public virtual ICollection<Eleve> Eleve { get; set; }
    }
}
